// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Infrastructure.Persistence;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706191319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_type");

                    b.Property<string>("ConditionValue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnimationClips")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("animation_clips");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ModelUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("ActionTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("action_tags");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("idx_chat_messages_session_created");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CondensedContext")
                        .HasColumnType("text")
                        .HasColumnName("condensed_context");

                    b.Property<Guid?>("CurrentCheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_checkpoint_id");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer")
                        .HasColumnName("turn_count");

                    b.HasKey("Id");

                    b.HasIndex("TravelerId")
                        .HasDatabaseName("idx_chat_sessions_traveler_id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CheckinRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckinAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkin_at");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<Guid>("ClientGeneratedId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_generated_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sync_status");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("TravelerId", "CheckinAt")
                        .HasDatabaseName("idx_checkin_records_traveler_checkin");

                    b.HasIndex("TravelerId", "CheckpointId", "ClientGeneratedId")
                        .IsUnique()
                        .HasDatabaseName("idx_checkin_records_idempotency");

                    b.ToTable("checkin_records", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Checkpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Radius")
                        .HasColumnType("integer")
                        .HasColumnName("radius");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.Property<Guid?>("StoryChapterId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_chapter_id");

                    b.HasKey("Id");

                    b.HasIndex("StoryChapterId");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("integer")
                        .HasColumnName("priority_score");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PriorityScore")
                        .HasDatabaseName("idx_partners_priority_score");

                    b.ToTable("partners", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PassportAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("OAuthProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oauth_provider");

                    b.Property<string>("OAuthUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("oauth_user_id");

                    b.HasKey("Id");

                    b.HasIndex("OAuthProvider", "OAuthUserId")
                        .IsUnique()
                        .HasDatabaseName("idx_passport_accounts_provider_user");

                    b.ToTable("passport_accounts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("ActivatedByTravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("activated_by_traveler_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_type");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("qr_code");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedByTravelerId");

                    b.HasIndex("QRCode")
                        .IsUnique()
                        .HasDatabaseName("idx_products_qr_code");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Stamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId");

                    b.HasIndex("TravelerId")
                        .HasDatabaseName("idx_stamps_traveler_id");

                    b.HasIndex("TravelerId", "CheckpointId")
                        .IsUnique()
                        .HasDatabaseName("idx_stamps_traveler_checkpoint");

                    b.ToTable("stamps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.StoryChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("region");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("UnlockCondition")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("unlock_condition");

                    b.HasKey("Id");

                    b.ToTable("story_chapters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_key");

                    b.Property<string>("ContentValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_value");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language_code");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode", "ContentKey")
                        .IsUnique()
                        .HasDatabaseName("idx_translations_lookup");

                    b.ToTable("translations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Traveler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnonymousId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("anonymous_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LinkedAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_account_id");

                    b.Property<string>("Preferences")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousId")
                        .IsUnique()
                        .HasDatabaseName("idx_travelers_anonymous_id");

                    b.HasIndex("LinkedAccountId");

                    b.ToTable("travelers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TravelerBadge", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.HasKey("TravelerId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("TravelerId")
                        .HasDatabaseName("idx_traveler_badges_traveler_id");

                    b.ToTable("traveler_badges", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TravelerVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("RedemptionCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("redemption_code");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id");

                    b.HasIndex("RedemptionCode")
                        .IsUnique()
                        .HasDatabaseName("idx_traveler_vouchers_redemption_code");

                    b.HasIndex("TravelerId")
                        .HasDatabaseName("idx_traveler_vouchers_traveler_id");

                    b.HasIndex("VoucherId");

                    b.ToTable("traveler_vouchers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("integer")
                        .HasColumnName("max_redemptions");

                    b.Property<decimal?>("MinimumSpend")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("minimum_spend");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("idx_vouchers_partner_id");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Domain.Entities.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.HasOne("Domain.Entities.Traveler", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CheckinRecord", b =>
                {
                    b.HasOne("Domain.Entities.Checkpoint", "Checkpoint")
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Traveler", "Traveler")
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");

                    b.Navigation("Traveler");
                });

            modelBuilder.Entity("Domain.Entities.Checkpoint", b =>
                {
                    b.HasOne("Domain.Entities.StoryChapter", "StoryChapter")
                        .WithMany()
                        .HasForeignKey("StoryChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StoryChapter");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.HasOne("Domain.Entities.Traveler", null)
                        .WithMany()
                        .HasForeignKey("ActivatedByTravelerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Domain.Entities.Stamp", b =>
                {
                    b.HasOne("Domain.Entities.Checkpoint", "Checkpoint")
                        .WithMany()
                        .HasForeignKey("CheckpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkpoint");
                });

            modelBuilder.Entity("Domain.Entities.Traveler", b =>
                {
                    b.HasOne("Domain.Entities.PassportAccount", null)
                        .WithMany()
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Domain.Entities.TravelerBadge", b =>
                {
                    b.HasOne("Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("Domain.Entities.TravelerVoucher", b =>
                {
                    b.HasOne("Domain.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Domain.Entities.Voucher", b =>
                {
                    b.HasOne("Domain.Entities.Partner", "Partner")
                        .WithMany("Vouchers")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Domain.Entities.Partner", b =>
                {
                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}

